# Configuration file for user constants
# These values will alter the bevhaviour of the prototype

# Ignore special prototype camera
excludes = ["20110901-0001-0001-0001-70b3d5f8a398"]

[shelf_monitoring]
# # Warp 2
# shelf_alcohol = [[1106, 339], [1847, 589], [1645, 941], [1072, 721]]
# Warp 3
shelf_alcohol = [[832, 286], [1847, 589], [1645, 941], [854, 628]]
# # Warp 3 with top
# shelf_alcohol = [[838, 153], [1905, 436], [1645, 941], [854, 628]]
